version: "3.5"

services:
  flatbot-backend:
    container_name: flatbot-backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    env_file:
     - ./apps/backend/.env.dev
    ports:
      - 3001:3001
    volumes:
      - ./apps/backend/:/app
      - /app/node_modules
    depends_on:
      - flatbot-postgres

  flatbot-frontend:
    container_name: flatbot-frontend
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
     - ./apps/frontend/.env.dev
    ports:
      - 3000:3000
    volumes:
      - ./apps/frontend/:/app
      - /app/node_modules

  flatbot-postgres:
    image: postgres:13.1
    container_name: flatbot-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: flatbotexample
      POSTGRES_DB: flatbot
      POSTGRES_USER: flatbot
    ports:
     - 5432:5432